- src/utils/SafeTransferLib.sol
`_GAS_STIPEND_NO_GRIEF` is reasonable in so many cases that it would be nice to have a version of this function that didn't require people typing it out each time.
new feature       ✨
> ✨ Add a two arg version of forceSafeTransferETH

- src/utils/LibBitmap.sol
First of all, thank you for building this beautiful library! I may have some of the libraries I wrote based on solady in the future once I test it more :)
This PR ports the scan forward and batch set/unset methods to the bitmap.
Since I haven't learned foundry, I only implement the test it with javascript.
https://github.com/estarriolvetch/solidity-bits/blob/solady/test/bitmap2.js
I will port the tests once I figure out how to do it. It will be welcome if anyone wants to help me on porting the tests!
- [v] Ran `npm run lint`?
> ✨ add scan forward and batch set/unset to bitmap

- src/utils/Multicallable.sol
🥢 Use `public` and `virtual` to conform to other Solady abstract contract style and permit overrides.
This is based on review of Auth contracts style.
> 🥢 Multicallable: Use `public` and `virtual`

- src/utils/SafeTransferLib.sol
Updates comments to better reflect reason for usage of force variants. Closes https://github.com/Vectorized/solady/issues/613
> 📝 Adjust SafeTransferLib docs to more accurately reflect vulnerability related to usage of force invariants

- src/accounts/ERC4337.sol
According to the [ERC-4337 spec](https://eips.ethereum.org/EIPS/eip-4337#definitions), the function visibility for validateUserOp should be external rather than public. Although this is probably the world's most annoying PR, the change will help implementations of ERC-4337 compliant smart wallet accounts that integrate custom logic in validateUserOp integrate solady, since those are using the 'external' visibility modifier instead of 'public', which creates a compiler error upon integration since Solidity does not support function overloading for external and public functions with the same name.
P.S. Thank you for all that you do with solady🫡
_Pull requests with an incomplete checklist will be thrown …
> ♻️ In ERC4337.sol, update validateUserOp visibility to 'external'

- src/utils/FixedPointMathLib.sol
Was working on porting the `FixedPointMathLib` for int128 and spent quite some time figuring out how some magic numbers were computed. Ended out that the comments were slightly wrong, so fixing this might help others as well.
**PS**: I'm facing a challenge with the implementations of `lnWad` and `expWad`. The documentation states that *'Care is taken to make sure ln(1) is exactly 0'* and *'Care is taken to make sure that exp(0) is exactly 1'*. However, I am struggling to achieve these exact values in int128. I would appreciate any guidance or insights you might have on this issue.
Thank you for developing this awesome lib!
> 🥢 Fix lnWad comments

- js/solady.js
I noticed the Javascript implementation of `LibZip.flzCompress` doesn't quite match the solidity version, which results in some different output on certain inputs.
Ths PR fixes the compression method to exactly match the output of the Solidity version (at least, in all of the inputs I've tested).
> 🐞 Fix Javascript LibZip.flzCompress

- src/utils/ReentrancyGuard.sol
> 🥢 Edit ReentrancyGuard comments

- src/utils/FixedPointMathLib.sol
As title. The updated threshold (via https://github.com/Vectorized/solady/pull/757) can be calculated using `math.log(1e-18) * 1e18` in Python (with a small precision loss in the last 3 digits).
> 🥢 Nit Comment in FixedMathPointLib

- src/utils/ERC1967Factory.sol
Bytecode comment for the implementation update have `06 0x20` as PUSH1 0x20, should be `60 0x20`
> 🥢 Fix typo in ERC1967Factory bytecode comment

- src/tokens/ERC721.sol
A minor change from `Emit {Transfer} event` to `Emit {Approval} event` for ERC721's `_approve(address,address,uint256)` comment.
Found that when comming across the contract.
> 📝 Minor Correct On ERC721 Comment

- src/utils/LibSort.sol
point to the correct name of the contract, from `Sort` to `LibSort`
Maybe create a symlink file or empty contract that imports libsort for sort as well, though thats up to you m8
> 🥢 Chore(natspec): correct the url for libsort

- .github/workflows/ci-all-via-ir.yml
- .github/workflows/ci.yml
- README.md
- foundry.toml
CI now checks solidity version 0.8.26
also updated the solidity badge in readme
> ✨ CI now uses new solidity version 0.8.26

- src/tokens/ERC1155.sol
With tender care, I ran `sed -i 's/Reveived/Received/g' ./src/tokens/ERC1155.sol`, each keystroke a gentle touch of affection.
In that moment, my heart swelled with a deep affection for the elegance of code, the harmony of syntax, and the beauty of precision.
> 🥢 Chore(natspec): ERC1155 function names

- src/utils/DynamicArrayLib.sol
- test/DynamicArrayLib.t.sol
> ⚡️ Optimize DynamicArrayLib

- src/utils/DynamicArrayLib.sol
- test/DynamicArrayLib.t.sol
Sometimes we don't need fancy syntax sugar.
> ✨ Add uint256 array functions to DynamicArrayLib

- README.md
- src/Milady.sol
- src/accounts/Pod.sol
- test/Pod.t.sol
- test/utils/mocks/MockPod.sol
> ✨ Minimal Pod

- src/tokens/ERC20.sol
In case for some reason, a version other than "1" is needed.
> ✨ Add overrideable _versionHash to ERC20

- src/utils/LibSort.sol
- test/LibSort.t.sol
> ✨ Add inSorted to LibSort

- src/utils/DynamicArrayLib.sol
- test/DynamicArrayLib.t.sol
For left-curved coding QoL.
Solidity is technically syntax sugar for bytecode anyways.
> ✨ Add indexOf and lastIndexOf to DynamicArrayLib

- src/utils/LibString.sol
> ⚡️ Tidy and optimize LibString

- src/utils/LibString.sol
- test/LibString.t.sol
Not a big issue, as escaping underscores will still work tho.
Just not faithful to the JavaScript implementation.
> 🐞 Add underscore to encodeURIComponent skipped characters

- src/utils/DynamicArrayLib.sol
- test/DynamicArrayLib.t.sol
> ✨ Add directReturn to DynamicArrayLib

- src/utils/LibClone.sol
- test/LibClone.t.sol
Sometimes, I just don't want to deploy a factory just to do an upgrade and call.
Steps for deployment:
```
1. Deploy the implementations with any create2 factory.
2. Craft an initcode for an ERC1967 bootstrap and deploy it with any create2 factory, 
with a salt of `bytes32(0)`. Grab the bootstrap address.
3. Craft an initcode for an ERC1967 proxy that points to that bootstrap.
4. Mine a vanity address salt for the ERC1967 proxy initcode, then deploy that ERC1967 proxy.
5. Use swissknife to do an upgrade and call on that proxy 
`abi.encodePacked(implementation, initCalldata)`.
```
> ✨ Allow ERC1967 bootstrap to do upgrade and call in a single call

- src/utils/g/EnumerableSetLib.sol
When an address set goes from fully initialized to zero elements to having elements again, the packing logic will errorneously leave the previous value in it. 
> 🐞 Fix AddressSet

- README.md
- src/Milady.sol
- src/tokens/ERC20.sol
- src/tokens/ERC20Votes.sol
- test/ERC20Votes.t.sol
- test/utils/mocks/MockERC20Votes.sol
> ✨ ERC20Votes

- src/utils/SafeTransferLib.sol
- test/SafeTransferLib.t.sol
> ♻️ Very safe transfer

- src/accounts/ERC1271.sol
- test/ERC1271.t.sol
- test/ERC4337.t.sol
- Removes `fields` and `extensions`.
- Change `contentsType` to `contentsDescription`, which offers an explicit mode to specify `contentsName`.
- Change the detection way to use `isValidSignature(0x7739...7739, <anySignature>`, which returns `0x77390001`. 
https://github.com/ethereum/ERCs/pull/687
> ♻️ Update ERC7739

- src/utils/SignatureCheckerLib.sol
> 📝 Fix SignatureCheckerLib Natspec

- src/utils/WebAuthn.sol
- src/utils/g/WebAuthn.sol
We'll use the struct case most often.
If `requireUserVerification` is false, then it will be optional.
> ⚡️ Optimize WebAuthn for struct case

- src/utils/EfficientHashLib.sol
- test/EfficientHashLib.t.sol
`abi.decode(a, (bytes32))` costs 90 more gas.
> ✨ Add convenience equality check

- test/LibString.t.sol
> ♻️ Fix LibString StringStorage test

- src/utils/SignatureCheckerLib.sol
> ⚡️ Optimize ERC6492 workflow

- src/utils/LibBytes.sol
- src/utils/g/LibBytes.sol
- test/LibBytes.t.sol
> ✨ LibBytes truncate 

- src/utils/P256.sol
- test/P256.t.sol
85 gas less than `abi.decode(encoded, (bytes32, bytes32))`.
> ✨ P256 decodePoint

- src/accounts/MinimalBatchExecutor.sol
- test/MinimalBatchExecutor.t.sol
- test/utils/mocks/MockMinimalBatchExecutor.sol
This might be renamed into an ERC.
> ✨ MinimalBatchExecutor

- src/accounts/MinimalBatchExecutor.sol
- test/MinimalBatchExecutor.t.sol
- test/utils/mocks/MockMinimalBatchExecutor.sol
Hmm... I'm not very convinced.
> ♻️ Convert MinimalBatchExecutor to 7579 style

- src/utils/P256.sol
- test/P256.t.sol
Cuz the stuff in `WebAuthn` are also named `tryDecode`.
The word `try` is intentionally included to signal that it is different from `abi.decode`, which will revert on invalid data.
> ♻️ Rename decode to tryDecode

- src/auth/EnumerableRoles.sol
- test/EnumerableRoles.t.sol
- test/utils/mocks/MockEnumerableRoles.sol
> ✨ Add checkOwnerOrRole to EnumerableRoles

- src/accounts/ERC7821.sol
- src/accounts/Timelock.sol
- test/ERC7821.t.sol
- test/utils/mocks/MockERC7821.sol
See, say if we expect it returns something, and someone uses 7821 for a 7579 contract, it will revert.
If people actually need the results, they can use traces.
> ♻️ Remove need to return results from ERC7821 execute

- src/utils/SignatureCheckerLib.sol
- test/SignatureCheckerLib.t.sol
> ♻️ Minimal ERC6492 non-reverting verifier

- src/accounts/Timelock.sol
- test/Timelock.t.sol
Changes:
- We have to ensure that `mode` is included in the `id`, otherwise someone can force timelock to execute without the `opData`, which will exclude the check for the `predecessor`. 
The `id` is now defined as `keccak256(abi.encode(mode, keccak256(executionData)))`.
- Use a `keccak256(abi.encodePacked(id, bytes9(_TIMELOCK_SLOT)))` for the slot of `id`. Let's just left-curve it to sleep better. After all, this contract is not supposed to be called frequently.
- Add comments to describe the encoding of `executionData`.
> ♻️ Timelock fixes

- src/accounts/LibERC7579.sol
> 🐞 Fix misplacement of selector in LibERC7579

- src/accounts/LibERC7579.sol
- test/LibERC7579.t.sol
Note that the runtime gas will increase if all args are not known on compile time.
> ⚡️ Allow encodeMode to be inlinable

- src/tokens/ERC20Votes.sol
CLOCK_MODE() is virtual, we need clock() to be virtual as well otherwise there's an issue with using mode=timestamp while returning a block.number.
We need clock() to be virtual in case users want timestamp based clock_mode
> 🥢 Update ERC20Votes clock to virtual so it can allow for timestamp clock_mode

- src/utils/SignatureCheckerLib.sol
- test/SignatureCheckerLib.t.sol
Fixes the ERC1271 case for the `isValidSignatureNow()` function that takes `bytes32 vs` as input, since it no longer shares the memory layout from the `ecrecover()` case. Also update one of the testcases to test this behavior.
> ♻️  Fix SignatureCheckerLib values

- src/utils/Initializable.sol
As a zero value can cause a logical error in the `initialize` modifier.
> ♻️ Initializable ensure _initializableSlot cannot be zero

- src/utils/UUPSUpgradeable.sol
Just for more safety, in case of some very unusual implementation that reverts on proxiableUUID and somehow returns that magic number.
> ♻️ UUPSUpgradeable explicit check on proxiableUUID staticcall success

- src/utils/LibClone.sol
```solidity
// If the extcodesize is too small, 
// `n` will be a big number that is around 0xffffffffff. 
// This will force the `extcodecopy` to OOG.
let n := and(0xffffffffff, sub(extcodesize(instance), 0x2d))
// We shall subtract `start` from `n`, so as to copy less bytes.
// The and `0xffffff` ensures that no underflow can happen.
// We don't want underflows to mess with our prep on `n`.
// If start is greater than `0xffffff`, we will still copy `n`. 
// Doesn't change the logic.
let l := sub(n, and(0xffffff, mul(lt(start, n), start)))
```
> ⚡️ Optimize argsOnClone

- src/utils/UUPSUpgradeable.sol
Now if call reverts then it read from `0x00` can't possible to read magic number from revert data bcs 1st bytes is always zero. 
> ⚡️ Optimize upgradeCall

- src/utils/LibBit.sol
- test/LibBit.t.sol
The `commonPrefix` function efficiently finds the common prefix (matching most significant bits) between two 256-bit numbers and returns it in hex format.
Potential Variations:
1. `commonBitPrefix` - Could return just the number of matching bits (similar to current implementation's internal use of `clz`)
2. `commonBytePrefix` - Could operate at byte granularity instead of nibbles (4 bits), which might be more useful for byte-oriented data like addresses or byte arrays
> ✨ Add commonPrefix

- test/SafeTransferLib.t.sol
> ♻️ Try fix stack-too-deep

- foundry.toml
`forge build` fails on Windows with https://github.com/foundry-rs/foundry/actions/runs/13068792712/job/36465786880#step:12:70 (see https://github.com/foundry-rs/foundry/pull/9797). This happens due to `"/*Transient*"` not matched (unclear now why it is on non win, going to be followed up in foundry)
Fixed by changing `"/*Transient*"` to `"*/*Transient*"`
[Non related]: with latest nightly forge builds tests are failing with `call didn't revert at a lower depth than cheatcode call depth;` message, this happens due to changed behavior of `expectRevert` please consider https://book.getfoundry.sh/cheatcodes/expect-revert#description
> 👷‍♂️ fix: build on Win fails due to transient skip

- src/tokens/ERC721.sol
- src/tokens/ext/zksync/ERC721.sol
- test/ERC721.t.sol
- test/Timelock.t.sol
> ♻️ Revert to the Original Implementation of ERC721

- src/utils/LibZip.sol
> ♻️ LibZip memsafe

- prep/memory-safe-scan.js
- src/accounts/EIP7702Proxy.sol
- src/accounts/ERC6551Proxy.sol
- src/tokens/ERC721.sol
- src/tokens/ext/zksync/ERC721.sol
- src/utils/DynamicArrayLib.sol
- src/utils/ECDSA.sol
- src/utils/LibBytes.sol
- src/utils/LibString.sol
- src/utils/g/DynamicArrayLib.sol
- src/utils/g/LibBytes.sol
- src/utils/g/LibString.sol
https://docs.soliditylang.org/en/latest/assembly.html#advanced-safe-use-of-memory
Beyond the strict definition of memory-safety given above, there are cases in which you may want to use more than 64 bytes of scratch space starting at memory offset 0. If you are careful, it can be admissible to use memory up to (and not including) offset 0x80 and still safely declare the assembly block as memory-safe. This is admissible under either of the following conditions:
- By the end of the assembly block, the free memory pointer at offset 0x40 is restored to a sane value (i.e. it is either restored to its original value or an increment of it due to a manual memory allocation), and the memory word at offset 0x60 is restored to a value of zero.
- The assembly block terminates, i.e. execution can …
> ♻️ More memory-safe annotations

- README.md
- foundry.toml
- src/Milady.sol
- src/accounts/EIP7702Proxy.sol
- src/accounts/LibEIP7702.sol
- test/EIP7702Proxy.t.sol
LibEIP7702 makes it neater to work with the proxy.
Principles:
- Try to preserve the upper 96 bits. Just in case some weird delegation saved some values in there.
- Use transient storage to pass the request. Technically, we can just use regular storage, without much overhead, cuz it's warm. But I am worried about the super edge case where someone actually use the upper 96 bits. Also it's cheaper for the case of direct delegation (no via EIP7702Proxy).
> ✨ Improve EIP7702Proxy and add LibEIP7702

- docs/utils/fixedpointmathlib.md
- src/utils/FixedPointMathLib.sol
- test/FixedPointMathLib.t.sol
> ✨ Coalesce

- src/accounts/EIP7702Proxy.sol
> 🥢 Nit EIP7702Proxy comments

- docs/utils/p256.md
- src/utils/P256.sol
- test/P256.t.sol
- test/utils/forge-std/Vm.sol
> ✨ P256 s normalized

- docs/accounts/erc6551.md
- docs/utils/callcontextchecker.md
- src/accounts/ERC6551.sol
- src/utils/CallContextChecker.sol
- test/ERC6551.t.sol
In case the owner isn't trusted.
> ♻️ Add extra protection for ERC6551

- src/tokens/ERC20.sol
Updated documentation to clarify that Permit2 is enabled by default and only requires overriding to disable.
https://github.com/Vectorized/solady/blob/09cdd7c8d4b4d83ab7b0c1e313df05310c4fc920/src/tokens/ERC20.sol#L668
> 🥢 Update Permit2 comment

- src/accounts/ERC4337.sol
Undo changes done in [465e41c](https://github.com/Vectorized/solady/commit/465e41c87238ca86972e38b07fb1176513a441ad) since ERC-4337 has been updated to define the presence of a `receive` function in the `EntryPoint`.
Closes: https://github.com/Vectorized/solady/issues/1365
> ⚡️ Use ERC-4337 `receive` again

- docs/utils/datetimelib.md
- docs/utils/dynamicarraylib.md
- docs/utils/dynamicbufferlib.md
- docs/utils/ecdsa.md
- docs/utils/enumerablemaplib.md
- docs/utils/libsort.md
- prep/gen-enumerable-map-lib.js
- src/utils/DynamicArrayLib.sol
- src/utils/DynamicBufferLib.sol
- src/utils/ECDSA.sol
- src/utils/EnumerableMapLib.sol
- src/utils/Initializable.sol
- src/utils/g/DynamicArrayLib.sol
- src/utils/g/DynamicBufferLib.sol
- src/utils/g/EnumerableMapLib.sol
> 🥢 Fix typos

- test/SafeTransferLib.t.sol
This pull request contains changes to improve clarity, correctness and structure.
> 🥢 Fix test typos

- docs/utils/libbytes.md
- docs/utils/libstring.md
- src/utils/LibBytes.sol
- src/utils/LibString.sol
- src/utils/g/LibBytes.sol
- src/utils/g/LibString.sol
- test/LibString.t.sol
> ✨ BytesStorage uint8At

- src/utils/LibZip.sol
- test/LibZip.t.sol
Faster better stronger.
Tbh, we really need a `clz` opcode.
> ⚡️ Optimize cdCompress and cdDecompress more

- test/LibPRNG.t.sol
- test/LibSort.t.sol
This PR corrects spelling mistakes in two test function names:
- `testLazyShufflerRevertsOnFinshedNext` -> `testLazyShufflerRevertsOnFinishedNext`
- `testSortChecksumed` -> `testSortChecksummed`
The changes are purely cosmetic and fix misspellings in function names without modifying any functionality.
Files modified:
- test/LibPRNG.t.sol
- test/LibSort.t.sol
> 🥢 Fix typos in test function names

- docs/utils/eip712.md
- src/utils/EIP712.sol
- test/EIP712.t.sol
- test/utils/mocks/MockEIP712.sol
- test/utils/mocks/MockEIP712Dynamic.sol
Safe usage is left to downstream.
> ✨ More EIP712 sans combos

- test/SignatureCheckerLib.t.sol
This PR fixes a typo in the function name by renaming:
- check_EcrecoverTrickEquivalance -> check_EcrecoverTrickEquivalence
- testEcrecoverTrickEquivalance -> testEcrecoverTrickEquivalence
The change corrects the spelling of "Equivalance" to "Equivalence" in the function names while maintaining the same functionality.
> 🥢 Rename check_EcrecoverTrickEquivalance function to fix typo

- src/utils/LibBit.sol
- test/LibBit.t.sol
> ✨ Count Zero Bytes

- docs/utils/libbit.md
- src/utils/LibBit.sol
> 📝 countZeroBytes fix Natspec, regen docs

- docs/utils/libbit.md
- src/utils/LibBit.sol
- test/LibBit.t.sol
> ✨ countZeroBytes for bytes

- test/LibBit.t.sol
- test/SemVerLib.t.sol
> ♻️ Strengthen tests

- test/SemVerLib.t.sol
> ♻️ Fix tests via-ir

- test/LibCWIA.t.sol
- test/LibClone.t.sol
Remove some unused imports in tests.
- [v] Ran `forge fmt`?
- [v] Ran `forge test`?
> ♻️ Remove unused import in test

- src/utils/LibBytes.sol
- src/utils/LibString.sol
- test/LibString.t.sol
Adds `function indexOfByte(bytes memory subject, bytes1 needle, uint256 from)` and offset-less shortcut to `LibBytes` and `LibString`.
This is a considerably more optimal version of `indexOf` in the case only a byte needle is used as we can apply some learnings from [bithacks](https://graphics.stanford.edu/~seander/bithacks.html) and keep the gas cost per 'missed' chunk quite low.
The reason for naming it `indexOfByte` versus keeping it as `indexOf` is because Solidity also tries to cast literal strings to `bytes1`, so if there's an implementation for `bytes` and one for `bytes1`, the user always has to be explicit on the type, which can get annoying.
Reproduced the `clz` implementation inside of it to avoid creating a dependency just for that and for a very small optimization, but it …
> ✨ LibBytes indexOfByte

- src/utils/LibSort.sol
No new memory allocations. O(n log n) average case using a very simple quicksort.
> ⚡️ Optimize groupSum

- docs/utils/merkletreelib.md
- src/utils/MerkleTreeLib.sol
- test/MerkleTreeLib.t.sol
> ✨ MerkleTreeLib pad default variant

- src/utils/Base58.sol
> ⚡️ Optimize Base58

- docs/utils/base64.md
- src/utils/Base64.sol
> 📝 Base64 headers

- docs/utils/enumerablemaplib.md
- prep/gen-enumerable-map-lib.js
- src/utils/EnumerableMapLib.sol
- src/utils/g/EnumerableMapLib.sol
- test/EnumerableMapLib.t.sol
> ✨ EnumerableMapLib capped variants

- src/accounts/ERC6551Proxy.sol
Found a tiny typo in the `ERC6551Proxy` where the optimization to allocate scratch space for the free memory pointer is described. In the current code, `6040608052` is used, which translates to `mstore(0x80, 0x40)`. Changed it to `6080604052`.
This is a super nit-picky one. Hope to provide a much more decent contribution in the future.
> 🥢  ERC6551Proxy typo fix

- docs/utils/efficienthashlib.md
noticed that the comparison was incorrectly using the original `bytes` value against the decoded `bytes32`, which can never be true.
updated the code to compare the decoded value to the correct `bytes32` variable.
this ensures the logic now works as intended.
📝
> 📝  docs: fix type mismatch in `abi.decode` comparison

- test/LibClone.t.sol
```markdown
Corrects a spelling error in function names within `test/LibClone.t.sol`.
- `testImplemenationOf` → `testImplementationOf`
- `testImplemenationOfGas` → `testImplementationOfGas`
```
> 🥢 Fix typo in LibClone.t.sol

- src/accounts/ERC7821.sol
- test/ERC7821.t.sol
- test/utils/mocks/MockERC7821.sol
The PR adds a new calldata optimized execution mode to ERC7821 which allows you to batch calls to the same target address, without sending the redundant "to" variable in each call.
It also removes the value field, and assumes it will be 0 for all the calls. This is usually true for most DeFi batches, because everything uses WETH.
Even if the `address(0)` optimization is used in calldata, for each call there is still a 4 gas overhead. 
With this PR, you can compress the calldata down to the theoretical optimal, this is specially useful when you want to do highly optimized self calls.
Note: The `address(0)` replacement is still available with the common `to` field passed.
_Pull requests with an incomplete …
> ✨ Add new calldata optimal execution mode for ERC7821
