src/utils/LibBitmap.sol, test/LibBitmap.t.sol, test/utils/mocks/MockLibBitmap.sol
=> ✨ Add LibBitmap

src/utils/MerkleProofLib.sol, test/MerkleProofLib.t.sol
This is to make things consistent with t11s' naming scheme in solmate.
=> ♻️ Rename MerkleProof to MerkleProofLib

src/utils/Multicallable.sol
dev note on possible double spend issues when batching calls with msg.value
=> 📋 Dev note on Multicallable

src/utils/LibString.sol, src/utils/SafeTransferLib.sol
To make headers code folding friendly.
Inspired by: https://github.com/transmissions11/solmate/pull/227 @devtooligan
=> ⭐ Kira kira headers

src/utils/ECDSA.sol
=> ♻️ Add ECDSA cautionary comment on zero addresses

src/utils/Multicallable.sol
This can cause an exploit / loss of funds, and should be a WARNING instead of a note.
=> ⚠️ Clarify multicallable warning

test/LibString.t.sol
Try to corrupt the memory before and after, and see if the string survives.
=> ♻️ Add stronger toString tests

src/utils/CREATE3.sol, src/utils/LibRLP.sol, src/utils/SSTORE2.sol
=> 📝 Update authors

README.md, src/utils/LibRLP.sol
=> 📝 Acknowledgements

src/utils/LibClone.sol
=> 📝 Clarify LibClone CWIA comments

test/LibSort.t.sol
=> ♻️ Optimize LibSort test

.gas-snapshot, src/utils/LibString.sol
=> 🥢 Fix escapeJSON comment

src/utils/LibString.sol
This PR fixes a small error in a comment.
I believe this qualifies as a nit               🥢
=> 🥢 Fix typo in LibString comment

src/utils/SignatureCheckerLib.sol
=> :chopsticks: Fix typos in sentence termination

test/LibClone.t.sol
=> ♻️ Strengthen LibClones test even more

src/utils/LibString.sol, test/DynamicBufferLib.t.sol, test/LibString.t.sol
=> 🐞 Fix LibString split

src/utils/DynamicBufferLib.sol
=> 🐞 Fix DynamicBufferLib

src/utils/SSTORE2.sol
Add the DATA_OFFSET constant to the library so it can be a drop-in replacement of solmate's SSTORE2
=> ✨ Add DATA_OFFSET for compatibility with solmate

src/Milady.sol
Cuz ain't nobody got time to type all the imports for quick and dirty prototyping.
=> ✨ Import everything

.github/workflows/ci.yml, foundry.toml
=> 👷‍♂️ Update ci

README.md, src/utils/EIP712.sol
=> ♻️ Tidy EIP712

README.md
This note will bring peace of mind to Solady users and further increase its sphere of influence.
=> 📝 Update README with note about upgradability

README.md
=> 📝 Add cautionary comment in README

src/utils/SSTORE2.sol
=> 🥢 Correct small typo in SSTORE2

src/utils/Clone.sol
Am auditing this for a client, mind your spelling optimizooor.
Cheers and very clean library!
\- Marco
=> Fix typo in comment

src/utils/RedBlackTreeLib.sol
=> 🥢 Correct RedBlackTreeLib comment

src/tokens/ERC20.sol
=> 🥢 Correct solmate ERC20 link

src/utils/EIP712.sol
For aesthetics, simplicity and gas-savings, incorporating use of `salt` into this implementation will be hard.
As such, we will leave a comment on the limitations of this implementation.
=> ♻️ Add EIP-712 comment on fields used

js/solady.js, js/solady.test.js
=> ♻️ Tidy and add more tests for JS

README.md
Make a note on how future solc versions may break Solady.
=> 📝 Edit README safety warning

src/auth/Ownable.sol, src/utils/DateTimeLib.sol, src/utils/DynamicBufferLib.sol, src/utils/SafeTransferLib.sol
- choosen -> chosen
- diffrent -> different
- Initalize -> Initialize
- overriden -> overridden
=> 📝 Correct typos

src/auth/Ownable.sol
While learning solidity, they said the good way to write function parameters is to start them with an underscore(_). (missed updating the function names, the better way for them will be without (_)).
thanks!
Correct me if I'm wrong.
optimization      ⚡️
=> 🥢 Fix Ownable comments

js/solady.js
=> 📝 Add more comments to solady.js

test/utils/mocks/MockERC1271Wallet.sol
More testing possibilities with contract wallets.
=> 📥 Add token receivers to MockERC1271Wallet.sol

src/utils/SafeTransferLib.sol
=> ⚡ transferAll ETH

README.md
To tell viewers which solc versions has Solady been tested on.
=> 📝 Add a Solidity badge to README

README.md
=> 📝 Update README Solidity badge

.github/workflows/ci-woke.yml
To avoid the recent intermittent failures.
=> 👷‍♂️ Make woke ci optional

src/tokens/ERC6909.sol
=> 🥢 Fix Typo Mistake on ERC6909

src/utils/JSONParserLib.sol
=> 🥢 Tidy JSONParserLib

js/solady.js
Hopefully this works. If you are a JSDoc expert, feel free to make a PR.
=> ♻️ Fix JSDoc

js/solady.d.ts, package.json
Surprisingly, not auto-generated.
=> ✨ Add .d.ts

src/tokens/ERC1155.sol, test/LibClone.t.sol
=> 🥢 Fix typos

.github/workflows/ci-all-via-ir.yml
=> 👷‍♂️ Fix ci-all-via-ir

docs/tokens/erc20.md
=> 📝 Completed ERC20 docs

docs/tokens/erc20.md
…reworded parts of the api reference and added the constants table
- Moved functions to h3
- Removed gas benchmarks
- Removed installation steps
- Removed the functions table
- Removed name of args
- Reworded api reference to make it clearer since the name of args have been removed.
- added constants table
=> 📝 Updates to ERC20 docs

.github/workflows/ci.yml
=> 👷‍♂️ Fix ci

test/FixedPointMathLib.t.sol
So that the challengers can pick off easier.
=> ♻️ Add lambertW0 test comments

src/utils/LibZip.sol
=> 🥢 Edit LibZip comment

.github/issue_template.md
=> 👷‍♂️ Add issue template

src/utils/ReentrancyGuard.sol
=> 🥢 Edit comment

src/utils/FixedPointMathLib.sol
Fixed the links to Uniswap's `FullMath.sol` and Remco Bloemen's `Mathemagic: exp and ln` blog post. 
=> 🥢 Nit FixedMathPointLib comments/links

src/tokens/ERC4626.sol
=> 🥢 Nit ERC4626 comment

src/utils/CREATE3.sol, src/utils/SSTORE2.sol
=> 🥢 Fix typo solmady => solady

.github/workflows/ci.yml
=> 👷‍♂️ Update ci to auto test for pull requests

src/accounts/ERC6551.sol
=> 🥢 Nit comments

.gitignore
Ignoring jetbrain settings in `.idea/`
=> 👷 Ignore jetbrain settings

src/utils/SignatureCheckerLib.sol
=> 🥢 Fix Typo in `SignatureCheckerLib`

src/accounts/ERC1271.sol, src/utils/LibPRNG.sol
=> 🥢 Fix typos in `ERC1271` and `LibPRNG`

.gas-snapshot, src/utils/ext/delegatexyz/DelegateCheckerLib.sol
=> 🥢 Nit typo in DelegateCheckerLib

src/auth/OwnableRoles.sol
- Adds notice regarding `_initializeOwner`, required for initialization when using `OwnableRoles`
- Fixes link `Ownable.sol` -> `OwnableRoles.sol`
=> 📝 docs: add notice and fix link in `OwnableRoles`

src/utils/ECDSA.sol
Replaced old links that no longer work.
=> 📝 Fix broken doc links

src/utils/LibClone.sol
Beacon proxies now auto verify on etherscan
=> 📝  Beacon proxies now auto verify on etherscan

.github/workflows/ci-super-intense.yml
=> 👷‍♂️ Add super intense ci

.gitattributes
=> 👷‍♂️ Add audits directory export-ignore to .gitattributes

.gitattributes
=> 👷‍♂️ Remove .gitattributes export-ignore, cuz it does nothing for forge install

src/utils/LibClone.sol, src/utils/SSTORE2.sol
=> 🥢 Fix some comments

src/utils/MetadataReaderLib.sol
=> 📝 Fix `readDecimals` comment

funding.json
=> 👷‍♂️ Add funding JSON

README.md, src/Milady.sol
=> 📝 Update Milady and README for DynamicArrayLib

.github/workflows/ci.yml
=> 👷‍♂️ Edit ci

src/utils/LibSort.sol
Just for checking the gas-diff CI workflow.
=> ⚡️ Optimize LibSort

test/DynamicArrayLib.t.sol
=> ♻️ Fix tests

src/utils/EnumerableSetLib.sol
=> ♻️ Fix EnumerableSetLib.Uint8Set.at

src/accounts/Pod.sol
=> 🥢 Nit Pod comment

src/utils/LibString.sol
"given enough eyeballs, all bugs are shallow"
=> Fix comment in LibString.sol

src/utils/URI.sol, test/URI.t.sol
Implement an exact replicate of `encodeURIComponent` and `decodeURIComponent` from Javascript, as it is useful for concatenating raw string data into URIs.
Included as many tests for edge cases as I could think of.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent
=> ✨ Feature: URI Component Encoding

src/utils/LibClone.sol, test/LibClone.t.sol
I'm so left-curved when coding.
=> ✨ Add createDeterministicClone

src/accounts/Pod.sol, test/utils/mocks/MockPod.sol
=> ♻️ Make Pod mothership internal

src/utils/DynamicArrayLib.sol, test/DynamicArrayLib.t.sol
=> ✨ Add more array casting functions

src/utils/LibClone.sol, src/utils/SSTORE2.sol
=> ♻️ Make args on functions revert if bytecode is too small

.github/CODEOWNERS
=> 👷‍♂️ Add codeowners

.github/CODEOWNERS
This is useless, as codeowners can't review their own PRs. 
Unless I make some kind of bot as the codeowner, which is a rabbit hole in itself.
=> 👷‍♂️ Remove codeowners

src/utils/LibClone.sol, test/LibClone.t.sol
=> ✨ Make ERC1967 bootstrap guarded

src/utils/LibClone.sol
=> ♻️ Add deployer argument to predictDeterministicAddressERC1967Bootstrap

.github/workflows/ci-all-via-ir.yml, .github/workflows/ci.yml, README.md, foundry.toml
=> 👷 Add solc 0.8.28 to CI

src/auth/EnumerableRoles.sol, src/utils/EnumerableSetLib.sol, test/EnumerableRoles.t.sol, test/EnumerableSetLib.t.sol, test/utils/mocks/MockEnumerableRoles.sol
=> ✨ EnumerableRoles

test/EnumerableRoles.t.sol, test/EnumerableSetLib.t.sol, test/utils/TestPlus.sol, test/utils/mocks/MockEnumerableRoles.sol
=> ♻️ Strengthen tests

src/auth/EnumerableRoles.sol, test/EnumerableRoles.t.sol
=> ⚡️ Optimize EnumerableRoles

.github/workflows/ci.yml
=> 👷‍♂️ Add `prep-checker` on CI

src/utils/SafeTransferLib.sol, test/SafeTransferLib.t.sol
=> ♻️ Add extcodesize checks to Permit2 ops

README.md, src/Milady.sol
=> 📝 Edit Milady and README

src/utils/WebAuthn.sol, src/utils/g/WebAuthn.sol
=> ♻️ Optimize and tidy WebAuthn encoding

src/utils/LibString.sol, src/utils/g/LibString.sol, test/LibString.t.sol
=> ✨ StringStorage

src/utils/LibString.sol, src/utils/g/LibString.sol, test/LibString.t.sol
=> ✨ Add isEmpty and length methods for StringStorage

src/utils/LibString.sol, src/utils/g/LibString.sol, test/LibString.t.sol
=> ⚡️ Optimize StringStorage

.github/workflows/ci-all-via-ir.yml, .github/workflows/ci.yml, foundry.toml, src/utils/ReentrancyGuardTransient.sol, test/ReentrancyGuardTransient.t.sol, test/utils/mocks/MockReentrancyGuardTransient.sol
=> ✨ ReentrancyGuardTransient

src/utils/LibString.sol, src/utils/g/LibString.sol, test/LibString.t.sol
Even lower gas and bytecode size.
=> ✨ Add setCalldata method for StringStorage

src/utils/LibTransient.sol, src/utils/g/LibTransient.sol, test/LibTransient.t.sol
=> ✨ LibTransient

src/utils/LibTransient.sol, src/utils/g/LibTransient.sol, test/LibTransient.t.sol
Make the thing revert with out-of-gas.
=> ♻️ LibTransient fix

src/utils/LibTransient.sol, src/utils/g/LibTransient.sol, test/LibTransient.t.sol
=> ✨ Add compat functions for LibTransient

src/utils/LibTransient.sol, src/utils/g/LibTransient.sol
=> ⚡️ Optimize LibTransient compat

src/utils/SignatureCheckerLib.sol, test/SignatureCheckerLib.t.sol
QoL change based on feedback. No one reads comments.
=> ♻️ Add ecrecover fallback to ERC6492 functions

src/utils/ECDSA.sol, src/utils/SignatureCheckerLib.sol, test/SignatureCheckerLib.t.sol
=> ⚡️ Optimize SignatureCheckerLib

src/utils/LibBytes.sol, src/utils/LibString.sol, src/utils/g/LibBytes.sol, src/utils/g/LibString.sol, test/LibBytes.t.sol
=> ✨ LibBytes

prep/eof-compat-analysis.js
=> 👷‍♂️ Add EOF compatibility analysis script

src/utils/WebAuthn.sol, src/utils/g/WebAuthn.sol, test/WebAuthn.t.sol
=> ♻️ Add WebAuthn plain verify method

src/utils/SignatureCheckerLib.sol, test/SignatureCheckerLib.t.sol
=> ♻️ Add extcodesize check to ERC6492 ecrecover fallback

src/utils/LibCall.sol
=> ⚡Optimize LibCall

src/utils/g/LibBytes.sol
=> ♻️ Run prep

README.md, src/Milady.sol, src/accounts/ERC7821.sol, test/ERC7821.t.sol, test/utils/mocks/MockERC7821.sol
Super nice number. Thanks @xinbenlv
=> ♻️ Rename to ERC7821

README.md, foundry.toml
Some addresses have 404, and some have redirected. This PR is to fix these problems
=> 🥢 Fix broken links

src/accounts/ERC7821.sol, test/utils/mocks/MockERC7821.sol
=> ♻️ Update ERC7821

src/accounts/ERC7821.sol, src/accounts/LibERC7579.sol, test/LibERC7579.t.sol
=> ✨ LibERC7579

src/utils/FixedPointMathLib.sol, test/FixedPointMathLib.t.sol
z3: 
```python
from z3 import *
a = Int('a')
b = Int('b')
x = Int('x')
y = Int('y')
ground_truth = a * b == x * y
N_BITS = 256
MAX_PLUS_ONE = 1 << N_BITS
MAX = MAX_PLUS_ONE - 1
ab = (a * b) % MAX_PLUS_ONE
c = (a * b) % MAX
xy = (x * y) % MAX_PLUS_ONE
z = (x * y) % MAX
computed = And(xy == ab, z == c)
solve(
a >= 0, a < MAX_PLUS_ONE,
b >= 0, b < MAX_PLUS_ONE,
x >= 0, x < MAX_PLUS_ONE,
y >= 0, y < MAX_PLUS_ONE,
ground_truth != computed
)
```
=> ✨fullMulEq

src/utils/FixedPointMathLib.sol, test/FixedPointMathLib.t.sol
=> ✨ fullMulDivN

src/accounts/ERC7821.sol, test/utils/mocks/MockERC7821.sol
=> ♻️ Add extraData for ERC7821

src/utils/LibBytes.sol, src/utils/g/LibBytes.sol, test/LibBytes.t.sol
=> ✨ LibBytes sliceCalldata and emptyCalldata

src/utils/EfficientHashLib.sol, src/utils/WebAuthn.sol, src/utils/g/WebAuthn.sol, test/EfficientHashLib.t.sol
=> ✨ SHA2-256

src/accounts/LibERC7579.sol, test/LibERC7579.t.sol
=> ✨ LibERC7579 reencodeBatch

rlp_tests.py, src/utils/LibRLP.sol, src/utils/g/LibRLP.sol, test/LibRLP.t.sol
Thanks: @AmadiMichael 
Do note: @RogerPodacter 
=> 🐞 Fix RLP encoding list edge case

src/accounts/ERC4337.sol, src/accounts/ERC6551.sol, src/accounts/Pod.sol, src/accounts/Receiver.sol, test/Pod.t.sol
=> ♻️ Move FnSelectorNotRecognized to Receiver

README.md, src/Milady.sol, src/accounts/ERC7821.sol, src/accounts/Timelock.sol, src/auth/EnumerableRoles.sol, test/Timelock.t.sol, test/utils/mocks/MockERC7821.sol
=> ✨ Timelock

src/utils/LibRLP.sol
I will do a separate run on prepping the files to avoid using this trick for EOF.
=> ♻️ Tidy LibRLP

prep/eof-compat-analysis.js
=> 👷‍♂️ Add returndatacopy OOG trick to EOF compat analysis

src/accounts/Timelock.sol, test/Timelock.t.sol
=> ♻️ Add admin role to Timelock

src/accounts/Timelock.sol
=> ⚡Optimize Timelock

src/accounts/Timelock.sol, test/Timelock.t.sol
=> ♻️ Fix Timelock

src/accounts/LibERC7579.sol, test/LibERC7579.t.sol
=> ✨ Add reencodeBatchAsExecuteCalldata

src/utils/WebAuthn.sol, src/utils/g/WebAuthn.sol, test/WebAuthn.t.sol
=> ⚡️ Optimize Webauthn struct compact encoding

prep/all.js, prep/gen-efficient-hash-lib.js, prep/gen-globalized-libs.js, prep/gen-safe-cast-lib.js
=> 👷‍♂️ prep/all

prep/common.js, prep/gen-efficient-hash-lib.js, prep/gen-globalized-libs.js, prep/gen-safe-cast-lib.js
=> 👷‍♂️ Update prep/all

src/accounts/Timelock.sol, test/Timelock.t.sol
=> ♻️ Strengthen Timelock tests

src/utils/SafeTransferLib.sol, test/SafeTransferLib.t.sol
=> ✨ Add totalSupply query to SafeTransferLib

src/utils/SafeTransferLib.sol, test/SafeTransferLib.t.sol
Getter convenience to efficiently and safely return ERC20 supply.
=> ✨ STL: totalSupply

src/utils/LibBytes.sol, src/utils/g/LibBytes.sol, test/LibBytes.t.sol
=> ✨ Add directReturn for bytes[]

prep/all.js, prep/gen-enumerable-map-lib.js, src/utils/EnumerableMapLib.sol, src/utils/EnumerableSetLib.sol, src/utils/g/EnumerableMapLib.sol, src/utils/g/EnumerableSetLib.sol, test/EnumerableMapLib.t.sol
=> ✨ EnumerableMapLib

README.md, src/Milady.sol
=> 📝 Update README and Milady

src/accounts/LibERC7579.sol, test/LibERC7579.t.sol
Thanks @MiloTruck!
https://gist.github.com/MiloTruck/fb126c0cba7c659f773fc627c3a244d6
=> ♻️ Add edge case check for zero pointers.length decode in LibERC7579

src/accounts/ERC4337.sol
=> ♻️ Allow entrypoint to skip the ERC7739 workflow

src/utils/FixedPointMathLib.sol
=> ✨ Add more ternary functions

src/utils/WebAuthn.sol, src/utils/g/WebAuthn.sol
=> ♻️ Fix WebAuthn SHA256 returndatasize check

src/utils/DynamicArrayLib.sol, src/utils/g/DynamicArrayLib.sol
=> ⚡️ Optimize DynamicArrayLib slice

src/accounts/ERC4337.sol
=> 🥢 Remove not in comment for ERC4337

src/utils/Lifebuoy.sol, test/Lifebuoy.t.sol
The left-curver (me), will always use one of the following workflows:
- Deploy via a factory with my own trusted EOA.
- Deploy via my own trusted EOA directly.
This implementation supports all the left-curved workflows safely.
The right-curver, who loves account abstraction and gas sponsorship, will have enough IQ to know to read the comments and override the function accordingly. 
=> ♻️ Simplify Lifebuoy

src/accounts/LibERC7579.sol
=> 🥢 Edit LibERC7579 comments

src/utils/LibBytes.sol, src/utils/g/LibBytes.sol
=> ⚡️ Optimize LibBytes storage check

src/tokens/ERC1155.sol, src/utils/LibTransient.sol, src/utils/Lifebuoy.sol, src/utils/g/LibTransient.sol
Godzamm.
This is actually required, cuz calldata slicing in plain Solidity will return slices that may not have the length immediately before the data.
=> ♻️ Safe calldata copying

src/utils/LibClone.sol, src/utils/SSTORE2.sol, test/DeploylessPredeployQueryer.t.sol
For short lengths, the gas might be higher.
=> ⚡️ LibClone argsOn reduce copied length

src/tokens/ERC1155.sol
=> ♻️ Try fix via-ir

src/accounts/LibERC7579.sol, test/LibERC7579.t.sol
=> ♻️ Clean the lower unused bytes of execType

src/accounts/LibERC7579.sol, test/LibERC7579.t.sol
I hope no more hidden gotchas. 
Letting this marinate for maybe a day first. 
=> ♻️ Add extra check for decodeBatch

src/utils/LibBytes.sol, src/utils/LibString.sol, src/utils/g/LibBytes.sol, src/utils/g/LibString.sol, test/LibBytes.t.sol
=> ✨ LibBytes cmp

src/tokens/ERC721.sol
=> ♻️ Make ERC721 overflow check safer

src/accounts/ERC7821.sol
Add comment on allowing entry point specific workflow.
=> 📝 Update ERC7821 comments

src/utils/LibClone.sol
=> 🥢 Nit LibClone Natspec

prep/gen-safe-cast-lib.js, src/utils/SafeCastLib.sol
=> 📝 Add natspec to SafeCastLib

src/utils/DynamicArrayLib.sol, src/utils/DynamicBufferLib.sol, src/utils/g/DynamicArrayLib.sol, src/utils/g/DynamicBufferLib.sol
=> 📝 Fix comment backticks

src/utils/SafeCastLib.sol
=> 📝 Add natspec on overflow error

prep/common.js, prep/gen-docs.js
=> 👷‍♂️ Tidy docs prep script

src/tokens/ERC721.sol
=> 🥢 ERC721 natspec nit

docs/accounts/erc1271.md, docs/accounts/erc4337.md, docs/accounts/erc4337factory.md, docs/accounts/erc6551.md, docs/accounts/erc6551proxy.md, docs/accounts/erc7821.md, docs/accounts/timelock.md, docs/auth/ownableroles.md, docs/tokens/erc1155.md, docs/tokens/erc20.md, docs/tokens/erc20votes.md, docs/tokens/erc4626.md, docs/tokens/erc6909.md, docs/tokens/erc721.md, docs/tokens/weth.md, docs/utils/datetimelib.md, docs/utils/deploylesspredeployqueryer.md, docs/utils/erc1967factoryconstants.md, docs/utils/libzip.md, docs/utils/lifebuoy.md, docs/utils/upgradeablebeacon.md, docs/utils/uupsupgradeable.md, prep/gen-docs.js
=> 👷‍♂️ Better docs gen

src/utils/LibBytes.sol, src/utils/g/LibBytes.sol
=> ⚡️ Optimize cmp

src/utils/Initializable.sol
Make uint64max a hardcoded constant for override safety.
Optimize version bit shifting.
=> ♻️ Initializable fixes

docs/index.html
=> 📝 Edit docs CSS

src/utils/ext/ithaca/BLS.sol, test/ext/ithaca/BLS.t.sol
Update precomplie address as per https://eips.ethereum.org/EIPS/eip-2537
=> ♻️ Update BLS as per EIP-2537

src/utils/SignatureCheckerLib.sol, test/SignatureCheckerLib.t.sol
=> ♻️ SignatureCheckerLib OZ style checks

src/utils/ext/zksync/SignatureCheckerLib.sol
Argh. If only there's a script to help me auto generate this.
=> ♻️ Fix zksync SignatureCheckerLib vs case

README.md, docs/tokens/erc20votes.md, docs/utils/libtransient.md, docs/utils/signaturecheckerlib.md, src/utils/LibTransient.sol, src/utils/g/LibTransient.sol
=> 📝 Fix LibTransient Natspec notice and regenerate docs

src/utils/SignatureCheckerLib.sol
=> ♻️ Make SignatureCheckerLib copying extra safe

src/utils/ext/zksync/SignatureCheckerLib.sol, test/ext/zksync/SignatureCheckerLib.t.sol
=> ♻️ Fix zksync SignatureCheckerLib and add tests

.github/workflows/ci.yml, foundry.toml, test/ext/zksync/ERC1155.t.sol, test/ext/zksync/ERC721.t.sol, test/ext/zksync/SafeTransferLib.t.sol, test/utils/mocks/ext/zksync/MockERC1155.sol, test/utils/mocks/ext/zksync/MockERC721.sol
=> ♻️ Add more zksync tests

src/utils/ext/zksync/ERC1967BeaconProxy.sol, src/utils/ext/zksync/ERC1967Factory.sol, src/utils/ext/zksync/ERC1967FactoryConstants.sol, src/utils/ext/zksync/ERC1967Proxy.sol, src/utils/ext/zksync/UpgradeableBeacon.sol
To prepare for upcoming zksolc changes.
=> ♻️ Tidy zksync

src/accounts/ERC7821.sol
=>  📝 Add BEBE comment to ERC7821

src/utils/ext/zksync/ERC1967Factory.sol, src/utils/ext/zksync/ERC1967FactoryConstants.sol, test/ext/zksync/ERC1967Factory.t.sol
=> ♻️ ZKsync tidy again

src/accounts/ERC7821.sol
=> 🥢 Fix ERC7821 incorrect comment

src/utils/Multicallable.sol
=> ⚡️ Multicallable results length fix

src/accounts/ERC4337Factory.sol, test/ERC4337Factory.t.sol
Change the API such that the salt includes the owner.
This design ensures that the creation cannot be replayed for a different owner on another chain regardless.
=> ♻️ ERC4337Factory combine owner and salt to ownSalt

src/accounts/ERC7821.sol
=> 🥢 ERC7821 add comment on skipping cleaning of upper 96 bits

src/accounts/Receiver.sol
=> 📝 Receiver add comment on assuming fmp size to save gas

src/accounts/LibERC7579.sol
=> ♻️ LibERC7579 add staticcall callType

src/accounts/Timelock.sol, test/Timelock.t.sol
=> ♻️ Timelock add MinDelaySet event in initialize

src/tokens/ERC20Votes.sol
https://github.com/OpenZeppelin/openzeppelin-contracts/blob/96b40d02c3fe836ffa19b6ed9217c3719c996f78/contracts/utils/structs/Checkpoints.sol#L264
=> 📝 ERC20Votes clarify comment to be explicit on less than or equal

src/utils/EnumerableSetLib.sol, src/utils/g/EnumerableSetLib.sol
=> 📝 EnumerableSetLib add comment on unstable order between removals

src/utils/MinHeapLib.sol, src/utils/g/MinHeapLib.sol
=> ♻️ MinHeapLib tweak and clarify enqueue abnormal use edge case

src/utils/EnumerableSetLib.sol, src/utils/g/EnumerableSetLib.sol
=> ⚡️ EnumerableSetLib remove redundant slot clearing

src/utils/RedBlackTreeLib.sol, src/utils/g/RedBlackTreeLib.sol
=> ⚡️ RedBlackTreeLib optimize fixup and other fixes

ext/wake/test_erc1155.py
=> 👷‍♂️ Fix Wake ERC-1155 test

src/utils/SafeTransferLib.sol, test/SafeTransferLib.t.sol
When `amount == 0`, it unapproves.
=> ♻️ SafeTransferLib Permit2 allow unapprove DAI

src/accounts/ERC4337.sol
=> ♻️ ERC4337 use depositTo instead of receive

src/utils/ext/delegatexyz/DelegateCheckerLib.sol
=> 📝 Fix incorrect DelegateCheckerLib ERC1555 comment

src/utils/ext/zksync/SafeTransferLib.sol, src/utils/ext/zksync/SingleUseETHVault.sol, test/ext/zksync/SafeTransferLib.t.sol
=> ♻️ Improve zksync single use ETH vault

src/utils/ext/zksync/SafeTransferLib.sol
=> ⚡️ Optimize zksync SafeTransferLib

src/accounts/Timelock.sol
Add comment on salt.
Add good-enough frontrunning protection.
=> ♻️ Timelock improvements

src/utils/LibClone.sol
=> 📝 Fix LibClone comment

docs/accounts/erc4337factory.md, docs/accounts/erc7821.md, docs/accounts/liberc7579.md, docs/accounts/timelock.md, docs/utils/enumerablesetlib.md, docs/utils/initializable.md, docs/utils/libclone.md, docs/utils/minheaplib.md, docs/utils/p256.md
=> 📝 Regenerate docs

src/accounts/ERC7821.sol
So that inheriting classes can use it optimally.
=> ✨ ERC7821 _get 

src/utils/LibSort.sol, test/LibSort.t.sol
=> ✨ LibSort groupSum

src/utils/LibBit.sol, test/LibBit.t.sol
=> ✨ Add commonPrefix

src/utils/DynamicArrayLib.sol, src/utils/g/DynamicArrayLib.sol, test/DynamicArrayLib.t.sol
=> ✨ DynamicArrayLib add copy and slice

src/utils/SafeTransferLib.sol, test/SafeTransferLib.t.sol
=> ✨ SafeTransferLib Permit2 approve and lockdown

src/utils/ext/zksync/delegatexyz/DelegateCheckerLib.sol
=> ✨ ZKsync DelegateCheckerLib

docs/tokens/erc20votes.md, src/tokens/ERC20Votes.sol
=> 📝 Edit ERC20Votes comment

docs/utils/libsort.md, src/utils/LibSort.sol, test/LibSort.t.sol
=> ⚡️ Optimize groupSum

test/SafeTransferLib.t.sol
=> ♻️ Fix SafeTransferLib Permit2 tests

.github/workflows/ci.yml
=> 👷‍♂️ Fix codespell

test/ext/zksync/SafeTransferLib.t.sol
=> ♻️ Fix zksync tests

src/accounts/ERC7821.sol, test/ERC7821.t.sol
=> ✨ ERC7821 batch of batches

LICENSE.txt
Updated the copyright year from 2022 to 2025 in the LICENSE file
=> 📝 Updated Copyright Year

src/utils/FixedPointMathLib.sol, test/FixedPointMathLib.t.sol
=> ✨ Saturating add and mul

docs/utils/fixedpointmathlib.md, src/utils/FixedPointMathLib.sol, test/FixedPointMathLib.t.sol
=> ♻️ Saturating

src/utils/LibStorage.sol, src/utils/g/LibStorage.sol, test/LibStorage.t.sol
=> ✨ LibStorage

src/utils/CallContextChecker.sol, src/utils/UUPSUpgradeable.sol, test/UUPSUpgradeable.t.sol, test/utils/mocks/MockUUPSImplementation.sol
Refactor it out of UUPSUpgradeable.
=> ✨ CallContextChecker

docs/utils/enumerablesetlib.md, src/utils/EnumerableSetLib.sol, src/utils/g/EnumerableSetLib.sol, test/EnumerableSetLib.t.sol
=> ✨ EnumerableSetLib update

README.md, docs/accounts/eip7702proxy.md, src/Milady.sol, src/accounts/EIP7702Proxy.sol, test/EIP7702Proxy.t.sol
=> ✨ EIP7702Proxy

docs/utils/callcontextchecker.md, src/utils/CallContextChecker.sol, test/CallContextChecker.t.sol, test/UUPSUpgradeable.t.sol, test/utils/mocks/MockCallContextChecker.sol, test/utils/mocks/MockUUPSImplementation.sol
=> ✨ CallContextChecker EIP7702 context checks

docs/index.html
=> 📝 Nit docs template

.github/workflows/ci.yml
=> 👷‍♂️ Update gas-diff CI

docs/utils/enumerablesetlib.md, src/utils/EnumerableSetLib.sol, src/utils/g/EnumerableSetLib.sol
=> ✨ EnumerableSetLib capped add

src/accounts/EIP7702Proxy.sol, test/EIP7702Proxy.t.sol
=> ♻️ Fix EIP7702Proxy and optimize

src/utils/CallContextChecker.sol
=> ♻️ Fix CallContextChecker EIP-7702 check

docs/accounts/eip7702proxy.md, docs/accounts/libeip7702.md, src/accounts/EIP7702Proxy.sol, src/accounts/LibEIP7702.sol, src/utils/CallContextChecker.sol
=> ♻️ Tidy 7702 code, regen docs

docs/utils/libbytes.md, src/utils/LibBytes.sol, src/utils/g/LibBytes.sol, test/LibBytes.t.sol
Tbh we are just trying to max extract on this one.
=> ✨ LibBytes calldata extractors

src/accounts/EIP7702Proxy.sol, test/EIP7702Proxy.t.sol
=> ⚡️ Optimize EIP7702Proxy for zero address default admin

docs/accounts/eip7702proxy.md, docs/tokens/erc20.md
=> 📝 Regen docs

src/utils/DynamicArrayLib.sol, src/utils/DynamicBufferLib.sol, src/utils/LibSort.sol, src/utils/g/DynamicArrayLib.sol, src/utils/g/DynamicBufferLib.sol, test/DynamicArrayLib.t.sol
If the capacity is zero, we are not allowed to extend the memory. 
=> 🐞 Fix p extend memory bug

docs/utils/fixedpointmathlib.md, src/utils/FixedPointMathLib.sol
HI! I fixed dead documentation link
=> 📝 fixed dead link

src/utils/P256.sol, test/P256.t.sol
=> ♻️ Make P256 non-reverting on invalid signatures

src/accounts/ERC7821.sol, test/ERC7821.t.sol
=> ♻️ Rename ERC7821 target -> to

foundry.toml, src/utils/P256.sol, test/P256.t.sol
Use more futureproof canary. Make tests work with `--odyssey`.
=> ♻️ Tidy P256

src/tokens/ERC6909.sol
=> 📝 Update ERC6909 transferFrom Natspec

src/utils/LibZip.sol
=> ⚡️ Optimize cdDecompress even more

src/utils/LibZip.sol, test/LibZip.t.sol
=> ⚡️ Optimize cdCompress and cdDecompress even more

README.md, docs/utils/semverlib.md, src/Milady.sol, src/utils/SemVerLib.sol, test/SemVerLib.t.sol
Should be pretty small and fast.
=> ✨ SemVerLib

test/FixedPointMathLib.t.sol
=> ♻️ Fix test

.github/workflows/ci.yml, docs/utils/libtransient.md, src/utils/LibTransient.sol, src/utils/g/LibTransient.sol, test/LibTransient.t.sol
=> ✨ TStack for generalized transient stack operations

docs/utils/libsort.md, src/utils/LibSort.sol, test/LibSort.t.sol
`O(n)`.
If only there's some `CLZ` opcode.
Anyways, the main bulk of gas is in the linear-probing loop.
=> ✨ LibSort hasDuplicate

test/LibSort.t.sol
=> ♻️ Strengthen test

src/utils/MerkleTreeLib.sol, test/MerkleTreeLib.t.sol
=> ⚡️ Optimize MerkleTreeLib

docs/utils/base58.md, src/utils/Base58.sol, test/Base58.t.sol
=> ✨ Base58 bytes32 specialization

docs/utils/base58.md, src/utils/Base58.sol, test/Base58.t.sol
=> ⚡️ Base58 decodeWord

README.md
=> 📝 Fix README logo

src/accounts/ERC7821.sol
=> ♻️ ERC7821 Swiss cheese dirty upper bits cleaning

src/utils/SafeTransferLib.sol, test/SafeTransferLib.t.sol
Enabled Mover test and fixed the implementation.
=> 🐞Fix safeMoveETH

.github/workflows/ci.yml, foundry.toml
=> 👷 Update EVM version in CI

test/utils/TestPlus.sol
=> 🥢 Fix typo in TestPlus
